
__CODES = \
    [("IS","Revenue","ITEM1"),
    ("IS","Other Revenue, Total","ITEM2"),
    ("IS","Total Revenue","ITEM3"),
    ("IS","Cost of Revenue, Total","ITEM4"),
    ("IS","Gross Profit","ITEM5"),
    ("IS","Selling/General/Admin. Expenses, Total","ITEM6"),
    ("IS","Research & Development","ITEM7"),
    ("IS","Depreciation/Amortization","ITEM8"),
    ("IS","Interest Expense(Income) - Net Operating","ITEM9"),
    ("IS","Unusual Expense (Income)","ITEM10"),
    ("IS","Other Operating Expenses, Total","ITEM11"),
    ("IS","Total Operating Expense","ITEM12"),
    ("IS","Operating Income","ITEM13"),
    ("IS","Interest Income(Expense), Net Non-Operating","ITEM14"),
    ("IS","Gain (Loss) on Sale of Assets","ITEM15"),
    ("IS","Other, Net","ITEM16"),
    ("IS","Income Before Tax","ITEM17"),
    ("IS","Income After Tax","ITEM18"),
    ("IS","Minority Interest","ITEM19"),
    ("IS","Equity In Affiliates","ITEM20"),
    ("IS","Net Income Before Extra. Items","ITEM21"),
    ("IS","Accounting Change","ITEM22"),
    ("IS","Discontinued Operations","ITEM23"),
    ("IS","Extraordinary Item","ITEM24"),
    ("IS","Net Income","ITEM25"),
    ("IS","Preferred Dividends","ITEM26"),
    ("IS","Income Available to Common Excl. Extra Items","ITEM27"),
    ("IS","Income Available to Common Incl. Extra Items","ITEM28"),
    ("IS","Basic Weighted Average Shares","ITEM29"),
    ("IS","Basic EPS Excluding Extraordinary Items","ITEM30"),
    ("IS","Basic EPS Including Extraordinary Items","ITEM31"),
    ("IS","Dilution Adjustment","ITEM32"),
    ("IS","Diluted Weighted Average Shares","ITEM33"),
    ("IS","Diluted EPS Excluding Extraordinary Items","ITEM34"),
    ("IS","Diluted EPS Including Extraordinary Items","ITEM35"),
    ("IS","Dividends per Share - Common Stock Primary Issue","ITEM36"),
    ("IS","Gross Dividends - Common Stock","ITEM37"),
    ("IS","Net Income after Stock Based Comp. Expense","ITEM38"),
    ("IS","Basic EPS after Stock Based Comp. Expense","ITEM39"),
    ("IS","Diluted EPS after Stock Based Comp. Expense","ITEM40"),
    ("IS","Depreciation, Supplemental","ITEM41"),
    ("IS","Total Special Items","ITEM42"),
    ("IS","Normalized Income Before Taxes","ITEM43"),
    ("IS","Effect of Special Items on Income Taxes","ITEM44"),
    ("IS","Income Taxes Ex. Impact of Special Items","ITEM45"),
    ("IS","Normalized Income After Taxes","ITEM46"),
    ("IS","Normalized Income Avail to Common","ITEM47"),
    ("IS","Basic Normalized EPS","ITEM48"),
    ("IS","Diluted Normalized EPS","ITEM49"),
    ("BS","Cash & Equivalents","ITEM50"),
    ("BS","Short Term Investments","ITEM51"),
    ("BS","Cash and Short Term Investments","ITEM52"),
    ("BS","Accounts Receivable - Trade, Net","ITEM53"),
    ("BS","Receivables - Other","ITEM54"),
    ("BS","Total Receivables, Net","ITEM55"),
    ("BS","Total Inventory","ITEM56"),
    ("BS","Prepaid Expenses","ITEM57"),
    ("BS","Other Current Assets, Total","ITEM58"),
    ("BS","Total Current Assets","ITEM59"),
    ("BS","Property/Plant/Equipment, Total - Gross","ITEM60"),
    ("BS","Accumulated Depreciation, Total","ITEM61"),
    ("BS","Goodwill, Net","ITEM62"),
    ("BS","Intangibles, Net","ITEM63"),
    ("BS","Long Term Investments","ITEM64"),
    ("BS","Other Long Term Assets, Total","ITEM65"),
    ("BS","Total Assets","ITEM66"),
    ("BS","Accounts Payable","ITEM67"),
    ("BS","Accrued Expenses","ITEM68"),
    ("BS","Notes Payable/Short Term Debt","ITEM69"),
    ("BS","Current Port. of LT Debt/Capital Leases","ITEM70"),
    ("BS","Other Current liabilities, Total","ITEM71"),
    ("BS","Total Current Liabilities","ITEM72"),
    ("BS","Long Term Debt","ITEM73"),
    ("BS","Capital Lease Obligations","ITEM74"),
    ("BS","Total Long Term Debt","ITEM75"),
    ("BS","Total Debt","ITEM76"),
    ("BS","Deferred Income Tax","ITEM77"),
    ("BS","Minority Interest","ITEM78"),
    ("BS","Other Liabilities, Total","ITEM79"),
    ("BS","Total Liabilities","ITEM80"),
    ("BS","Redeemable Preferred Stock, Total","ITEM81"),
    ("BS","Preferred Stock - Non Redeemable, Net","ITEM82"),
    ("BS","Common Stock, Total","ITEM83"),
    ("BS","Additional Paid-In Capital","ITEM84"),
    ("BS","Retained Earnings (Accumulated Deficit)","ITEM85"),
    ("BS","Treasury Stock - Common","ITEM86"),
    ("BS","Other Equity, Total","ITEM87"),
    ("BS","Total Equity","ITEM88"),
    ("BS","Total Liabilities & Shareholders' Equity","ITEM89"),
    ("BS","Shares Outs - Common Stock Primary Issue","ITEM90"),
    ("BS","Total Common Shares Outstanding","ITEM91"),
    ("CS","Net Income/Starting Line","ITEM92"),
    ("CS","Depreciation/Depletion","ITEM93"),
    ("CS","Amortization","ITEM94"),
    ("CS","Deferred Taxes","ITEM95"),
    ("CS","Non-Cash Items","ITEM96"),
    ("CS","Changes in Working Capital","ITEM97"),
    ("CS","Cash from Operating Activities","ITEM98"),
    ("CS","Capital Expenditures","ITEM99"),
    ("CS","Other Investing Cash Flow Items, Total","ITEM100"),
    ("CS","Cash from Investing Activities","ITEM101"),
    ("CS","Financing Cash Flow Items","ITEM102"),
    ("CS","Total Cash Dividends Paid","ITEM103"),
    ("CS","Issuance (Retirement) of Stock, Net","ITEM104"),
    ("CS","Issuance (Retirement) of Debt, Net","ITEM105"),
    ("CS","Cash from Financing Activities","ITEM106"),
    ("CS","Foreign Exchange Effects","ITEM107"),
    ("CS","Net Change in Cash","ITEM108"),
    ("CS","Cash Interest Paid, Supplemental","ITEM109"),
    ("CS","Cash Taxes Paid, Supplemental","ITEM110")]

name_dict        = {k : (f, c) for f, k, c in __CODES}
name_dict_keys   = [k for f, k, c in __CODES]

name_I_dict      = {k : (f, c) for f, k, c in __CODES if f == "I"}
name_I_dict_keys = [k for f, k, c in __CODES if f == "I"]

name_B_dict      = {k : (f, c) for f, k, c in __CODES if f == "B"}
name_B_dict_keys = [k for f, k, c in __CODES if f == "B"]

name_C_dict      = {k : (f, c) for f, k, c in __CODES if f == "C"}
name_C_dict_keys = [k for f, k, c in __CODES if f == "C"]
